version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kayak_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: kayak_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kayak_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kayak
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20
    container_name: kayak_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

volumes:
  db_data: